version: '3.8'

services:
  db:
    image: postgres:15
    container_name: subscription_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions_db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  app:
    build: .
    container_name: subscription_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=subscriptions_db
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./swagger.yaml:/app/swagger.yaml
